package me.outspending.protocol;

public enum GameEvent {
    NO_RESPAWN_BLOCK_AVAILABLE,
    BEGIN_RAINING,
    END_RAINING,
    CHANGE_GAME_MODE,
    WIN_GAME,
    DEMO_EVENT,
    ARROW_HIT_PLAYER,
    RAIN_LEVEL_CHANGE,
    THUNDER_LEVEL_CHANGE,
    PLAY_PUFFERFISH_STING_SOUND,
    PLAY_ELDER_GUARDIAN_MOB_APPEARANCE,
    ENABLE_RESPAWN_SCREEN,
    LIMITED_CRAFTING,
    START_WAITING_FOR_CHUNKS
}
